services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "9000:9000"
    environment:
      - CI=true
volumes:
  node_modules:

networks:
  app_net:
    external: true
