services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:delegated
      - vendor:/var/www/html/vendor
    environment:
      TZ: America/Sao_Paulo
    networks: [app_net]

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-u","root","-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks: [app_net]

  server:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_started
      mysql:
        condition: service_healthy
    networks: [app_net]

  composer:
    image: composer:2.7
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
      - composer_cache:/tmp/composer
    entrypoint: ["composer","--ignore-platform-reqs"]
    networks: [app_net]

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    entrypoint: ["php","/var/www/html/artisan"]
    networks: [app_net]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks: [app_net]

networks:
  app_net:
    name: app_net
    driver: bridge

volumes:
  dbdata:
  composer_cache:
  vendor:
